### ISSUE TITLE
startup issues

### ISSUE THREAD

**Issue by Cezus** [hatl/hasscontrol#10]
Hello,
I encounter the following findings:
- When using a long lived token, https://[url] gets me 'authentication failed'
- When using a long lived token, https://[url]/api/ does authenticate but message 'group not found' is displayed
- When removing the long lived token in ConnectIQ, after log in with url https://[url], group is found and entities can be used.

**Comment by brzozow** [comment]
I can confirm problems with long lived token. In my case I can't authenticate using long lived token
