### ISSUE TITLE
Failed. unknown error code -400

### ISSUE THREAD

**Issue by SleepyBlueCat** [hatl/hasscontrol#12]
I have installed via the IQ app. my nabu casa https and a long live token. created a group with 3 light entities. reloaded groups section in home assistant en then the watch. then the watch gives this error.
screenshots can be provided

**Comment by SleepyBlueCat** [comment]
never mind, a fresh re-install on the watch and a new acces token solved it

**Comment by serbani** [comment]
I have the same problem after switching from Android to iOS on the phone.
Unfortunately a fresh install of the watch app and a new long lived access token didn't change anything. 
The home assistant instance is local and the token works fine using cURL.
Any suggestions? Thanks.
