### ISSUE TITLE
unable to refresh entities

### ISSUE THREAD

**Issue by BGOtura** [hatl/hasscontrol#17]
Hi,

I have managed to connect to my HA using a long-lived access token.

My configuration in Connect IQ HA settings is:

Scenes: <empty>
Group: group.garmin

My config in HA helpers is as below:

![image](https://user-images.githubusercontent.com/49201730/226102174-743f0ac6-ae75-4bd0-8417-e4f51a5f4644.png)

When I do a "Refresh entities" I get on the watch:

> Failed
> Unknown error
> code -300

It also seems to trigger this on HA´s log:

`2023-03-18 11:25:43.732 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"`

Any ideas?

**Comment by hatl** [comment]
hi
which HA version are you using?
i ran into the same issue a few days ago.
it disappeared after the update to 2023.3.5

**Comment by BGOtura** [comment]
I was using and old version from November 22, but have now updated to the latest  2023.3.5 and face the same issue.

**Comment by gypas1501** [comment]
I've had the same problem as author (Unknown error -300). I did a little bit of troubleshooting and it turns out it was caused by my self signed certificate even though cert is installed and working in my android (Using Caddy as reverse proxy with self signed cert). When I exposed HA instance to internet (using duckdns with LetsEncrypt certificate) everything started to work.

@hatl is there a way to make self signed cert working? I would prefer using VPN to access my HA instance rather than exposing it to the internet

**Comment by Jaytie2k7** [comment]
I can now also confirm that. When I use my self signed certificate, that I imported to my android device the widget refuses to refresh the entities with error code 300. 
I use my self signed certs with Nginx Proxy Manager. 
When I expose my HA instance to the web with an let's encrypt certificate, it works. 

It would be really great if self signed certificates would also work, because I don't want to expose my home assistant to the internet just to use the widget.

**Comment by hatl** [comment]
I'm using caddy to get the certificates and home assistant is only available in the LAN and the following Caddyfile:

```
home-assistant.mydomain.com {
    @internal {
        remote_ip 192.168.0.0/24
    }
    handle @internal {
      reverse_proxy 192.168.0.1:8123 {
        header_up X-Forwarded-Host {host}
      }
    }
    respond 403
}
```

**Comment by F13** [comment]
I don't understand this resolution...I get a similar error using an internal-only TLS certificate. Is there any way to allow more general TLS connectivity? The connectivity works totally fine from my Android device.

**Comment by aqwserf** [comment]
@hatl : agree with @F13 . Just received my Venu 3 and wanted to your application but I'm getting the same error with a self-signed certificate. The API token works fine. I'm using the buit-in Nginx module.
According to your configuration file, the nginx default one seems pretty much the same:
```
core-nginx-proxy:/# cat /etc/nginx.conf
daemon off;
error_log stderr;
pid /var/run/nginx.pid;

events {
	worker_connections 1024;
}

http {
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server_tokens off;

    server_names_hash_bucket_size 128;
	
    # intermediate configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

    #include /data/cloudflare.conf;
	
    server {
        server_name _;
        listen 80 default_server;
        listen 443 ssl http2 default_server;
        ssl_reject_handshake on;
        return 444;
    }

    server {
        server_name ha.hysteresis.lan;

        # These shouldn't need to be changed
        listen 80;
        return 301 https://$host$request_uri;
    }

    server {
        server_name ha.local.lan;

        ssl_session_timeout 1d;
        ssl_session_cache shared:MozSSL:10m;
        ssl_session_tickets off;
        ssl_certificate /ssl/local.lan.crt;
        ssl_certificate_key /ssl/local.lan.key;

        # dhparams file
        ssl_dhparam /data/dhparams.pem;

        listen 443 ssl http2;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        proxy_buffering off;

        #include /share/nginx_proxy_default*.conf;

        location / {
            proxy_pass http://homeassistant.local.hass.io:8123;
            proxy_set_header Host $http_host;
            proxy_redirect http:// https://;
            proxy_http_version 1.1;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header X-Forwarded-Host $http_host;
        }
    }

    #include /share/nginx_proxy/*.conf;
}
```

BTW, a couple of comments regarding the logging process:
```
To login, simply open the widget and trigger any scene. Shortly after, you will see a sign in request on your smartphone. Complete the sign in process on your phone and return to the watch.
```
I did create a scene and triggered it (using my laptop) after opening the widget (and click on `login`, but all I got is a black screen.

```
If you don't have any scenes, you can login by hold the menu button on your watch and logging in from them widget menu.```
This is the process I followed and I get a blackscreen.

and FYI, I've added my self-signed certificate to my phone and the application (Companion) works well, as well as with Chrome.

Thanks!

**Comment by hatl** [comment]
the Garmin API doesn't allow the usage of self-signed certificates - for good reasons (security)

importing them on the phone only makes them available on the phone
they would have to be added on the watch (which is  - as far as i know - currently not possible)

so having an "official" SSL certificate is currently a must-have
you can get them either by using the caddy config i provided or by buying a certificate - those have become quite cheap

**Comment by F13** [comment]
Does the watch communicate directly with the services over HTTPS? It doesn't go through your connected mobile (Android/Apple)?

**Comment by hatl** [comment]
> Is there any option in the Garmin API to simply skip certificate validation?
Unfortunately not - the documentation of the corresponding method (makeWebRequest) can be found here: https://developer.garmin.com/connect-iq/api-docs/Toybox/Communications.html#makeWebRequest-instance_function

> I would have to setup DNS resolution for a globally accessible domain that points to my infrastructure
yes.
you could use Duck DNS and Dnsmasq
there are Home Assistant add-ons for both
Duck DNS can be configured to use Let's Encrypt SSL certificates

> Does the watch communicate directly with the services over HTTPS?
Its being "tunneled" trhough the bluetooth connection to the phone, but the actual connection is established between the Garmin device and Home Assistant. This is why adding the SSL certificates on the phone doesn't help.

**Comment by aqwserf** [comment]
@F13 agree for the security, and yeah, it's unfortunate. 
@hatl thanks for the doc.

As a workaround, it could be possible to retrieve a genuine LE certificate and use a local DNS to fake the IP address

**Comment by F13** [comment]
My CA cert is fully installed and trusted on my Android already. It doesn't appear that Garmin Connect uses the Android certificates.

**Comment by aqwserf** [comment]
I finally managed to find a way using the following steps:

1. request a certificate from let's encrypt (e.g ha.example.com)
2. add a `A` entry on your DNS provider to point to your reverse proxy internal IP
3. copy the certificate to a server handling the reverse proxy
4. add this proxy to the `trusted_proxies` in HA
5. configure the app to point to your domain
6. (optional) add a `list rebind_domain` in case you get a `DNS-rebind attack detected` with OpenWRT

It's probably possible to bypass the reverse to point to HA directly (Nginx) but the certificate provided by LE doesn't seem to be recognize by Nginx (most probably a format issue)

**Comment by JaviBite** [comment]
> I'm using caddy to get the certificates and home assistant is only available in the LAN and the following Caddyfile:
> 
> ```
> home-assistant.mydomain.com {
>     @internal {
>         remote_ip 192.168.0.0/24
>     }
>     handle @internal {
>       reverse_proxy 192.168.0.1:8123 {
>         header_up X-Forwarded-Host {host}
>       }
>     }
>     respond 403
> }
> ```



Hi im trying this i have my CA (self-signed) trusted in my phone, and a cert is signed by that CA and using it in my Caddy file for all my subdomaings my Caddy is like


```
*.pelis.casa {
    tls server.pem server.key.pem
}

qbit.pelis.casa {
	reverse_proxy localhost:8085
}

# More subdomains and then your code

ha.pelis.casa {
    @internal {
        remote_ip 192.168.1.0/24
    }
    handle @internal {
        reverse_proxy 192.168.1.60:8123 {
        header_up X-Forwarded-Host {host}
      }
    }
    respond 403
}
```

But I still get the -300 code how can I solve or maybe I didn't understand this phrase "you can get them either by using the caddy config I provided or by buying a certificate" but I understand that I can make it work just with caddy.

Thank you!

**Comment by hatl** [comment]
see https://github.com/hatl/hasscontrol/issues/17#issuecomment-1894111858

**Comment by JaviBite** [comment]
I got a real SSL cert for my duckdns domain and then add that domain in my dns resolver (pihole) to point to my home assistant so my caddy looks like

mydomain.duckdns.org { 
		
    tls mydomain.cer mydomain.key #real certs 
    @internal {
        remote_ip 192.168.1.0/24
    }
    handle @internal {
        reverse_proxy 192.168.1.60:8123 {
        header_up Host {host}
      }
    }
    respond 403
}

I obtained the certs doing this
```
export DuckDNS_Token="duckdns_token
acme.sh --issue --dns dns_duckdns -d mydomain.duckdns.org
```

It works in every device but the garmin, I read all of this issue but I don't know what to do to make it work

**Comment by hatl** [comment]
You don't have to manually fetch the certificates. Caddy will do this for you if you remove the tls line.

Did you remove your self-signed certificates from your phone?
This will allow you to check if you are really using the new certificates.
You can also check the certificate info on your phone by using e.g., the Chrome browser.
Make sure that it shows "Organization (O): Let's Encrypt"

**Comment by JaviBite** [comment]
If i remove the tls now it says "ERR_SSL_PROTOCOL_ERROR" (from PC)
The Organization its empty in the domain cert but the root is 

Issuer: C = AT, O = ZeroSSL, CN = ZeroSSL ECC Domain Secure Site CA

**Comment by hatl** [comment]
Please double-check your Caddy config. E.g., do you have a global tls statement?
Please also check the Caddy log - you should see the certificate requests.

Make sure that your internal DNS entry points to the Caddy host and not to the Home Assistant host.

**Comment by JaviBite** [comment]
Okay it seems the certificate request is failing with the challenge,

2025/04/06 15:24:08.335 ERROR   http.acme_client        challenge failed        {"identifier": "mydomain.duckdns.org", "challenge_type": "http-01", "problem": {"type": "urn:ietf:params:acme:error:connection", "title": "", "detail": "X.X.X.X: Fetching http://mydomain.duckdns.org/.well-known/acme-challenge/RJBKGbXP6aTf6XM15-gEzuWHcLTbYoMiuHBIS5xi20Y: Timeout during connect (likely firewall problem)", "instance": "", "subproblems": []}}
2025/04/06 15:24:08.338 ERROR   http.acme_client        validating authorization        {"identifier": "mydomain.duckdns.org", "problem": {"type": "urn:ietf:params:acme:error:connection", "title": "", "detail": "X.X.X.X: Fetching http://mydomain.duckdns.org/.well-known/acme-challenge/RJBKGbXP6aTf6XM15-gEzuWHcLTbYoMiuHBIS5xi20Y: Timeout during connect (likely firewall problem)", "instance": "", "subproblems": []}, "order": "https://acme-v02.api.letsencrypt.org/acme/order/1966874396/371380385307", "attempt": 1, "max_attempts": 3}

My internal DNS points to caddy host

I Have a global but with a wildcard for other domains 

```
*.pelis.casa {
    tls server.pem server.key.pem
}
```

**Comment by hatl** [comment]
I'm sorry, but this is not related to hasscontrol or this issue ([unable to refresh entities](https://github.com/hatl/hasscontrol/issues/17#top))
Someone would need to check your config files (Caddy, router, Home Assistant, ...) and the certificate chain.
If you are looking for further support, you might want to consider something like https://www.fiverr.com/
