### ISSUE TITLE
add support for new Fenix and Epix Pro

### ISSUE THREAD

**Issue by tube0013** [hatl/hasscontrol#22]
Just updated watches, can these get added so they can be installed on the new devices?

thanks!

**Comment by Veldkornet** [comment]
Any news on this? Or do we need to find a new fork again?

**Comment by hatl** [comment]
feel free to provide a pull request
as with many open source projects: i'm doing this in my free time :wink:

**Comment by Veldkornet** [comment]
Fixed by #26

**Comment by hatl** [comment]
thanks
