### ISSUE TITLE
Is there any way to set this app as my shortcut app?

### ISSUE THREAD

**Issue by ccbell42** [hatl/hasscontrol#24]
This app is working great for me on my Venu 2, the only thing that would make it more convenient is if I could set it as my shortcut app (when I swipe right on my watch). Is this possible to do? The app doesn't currently show up in my list of shortcut options; I don't know if that list is hard-coded or if there's a way to add an app to it.

**Comment by Floris3** [comment]
Not a direct answer to your question, but my solution is to set the app as the bottom/lowest glance, that way when I push 'up' the first thing that i see is HassControl. Then a press on the start button gets me in Hasscontrol. Two button shortcut so to speak.
