### ISSUE TITLE
Wi-fi enabled devices

### ISSUE THREAD

**Issue by IlPicasso** [hatl/hasscontrol#29]
Hello, 

I am wondering, there are some watches like Vivoactive 4 that has wi-fi feature.

Is it possible to make Hasscontrol work with wifi?

**Comment by hatl** [comment]
As far as I know, there is currently no possibility to do API calls via WiFi.
It would also cause quite some delay since WiFi is usually not connected.

**Comment by Aaroneisele55** [comment]
I would suggest you to reopen this, as an API for WiFi-HTTP-Requests now exists and could be implemented. I might even try and implement it myself when I'll have time to do it, but I don't know which SDK Version the Widget uses, because with the latest, it won't build.

**Comment by hatl** [comment]
which API functions are you referring to?

**Comment by Aaroneisele55** [comment]
> 
> which API functions are you referring to?

https://developer.garmin.com/connect-iq/core-topics/downloading-content/

The section "WiFi Bulk Downloads" describes what could be used as a fallback (if the phone is not connected, try to use WiFi instead)

**Comment by hatl** [comment]
I've also looked into that one.
The main drawback would be what i mentioned earlier:

>  It would also cause quite some delay since WiFi is usually not connected.

Some options, advantages and disadvantages were discussed here: https://forums.garmin.com/developer/connect-iq/f/discussion/194836/rest-api-over-wifi

Would be great if you want to look into this further.
Maybe it is possible to add it as a second option for calling the home assistant api.

Currenltly, the minimum API version is 3.1.0 (which supports the bulk download feature) - see: https://github.com/hatl/hasscontrol/blob/master/widget/manifest.xml
