### ISSUE TITLE
Add Device Support: Fenix 3

### ISSUE THREAD

**Issue by sh0nuff** [hatl/hasscontrol#40]
Hello! I was overjoyed to discover this updated fork, is there any possibility to add support for the Fenix 3, or is it too old to make this possible?

**Comment by hatl** [comment]
hi
unfortunately it's too old
fenix 3 supports API level 1.4.0, but at least 3.1.0 would be needed
sorry

**Comment by sh0nuff** [comment]
Ah! Thanks, I figured, appreciate you taking the time to reply!
