### ISSUE TITLE
Gesture support for 5S

### ISSUE THREAD

**Issue by levexis** [hatl/hasscontrol#46]
I can't get past the first list of HA items. These work fine but I cant get to the groups or the settings.

I suspect this is because the watch has 2 buttons. The first two screens are tap to continue, after that tap turns the lights on and off.

Any chance of adding swiping left? The buttons don't do anything either.

As a work around is there any other way to force the config to be reloaded, like cycling the power?

**Comment by hatl** [comment]
hi
what about holding the button on the bottom-right?
from what i can see in the manual, this should show the menu.

**Comment by levexis** [comment]
That seems to work for me now, so you can close this :)
