### ISSUE TITLE
code -300

### ISSUE THREAD

**Issue by Leberwurstmensch** [hatl/hasscontrol#59]
Hi I´ve the following issue:

1: I setup the widget as described 
2: Widget is setup with my Home Assistant via long lived access token.
3: Try to integrate scene "scene.gamin1" by typing "garmin1" in  Connect IQ Settings
4: Scene "garmin1" is on my Watch but when I press it I get "FAILED Unknown error code -300"

For Troubleshooting I tried also filling with "scene.garmin1" or adding all Lights for this scene to one goup and adding this group to Connect IQ Settings.

Do I need the Group settings? When I understand the Description correctly I only need to setup and fill in my scenes to Connect IQ Settings?

**Comment by hatl** [comment]
Using the scene name only should be fine.
Unfortunately, I cannot reproduce the issue - scenes work for me.
Which Garmin device are you using? I'll check it in the simulator.

**Comment by cypissa** [comment]
Hi! I'm encountering the same problem: "FAILED Unknown error code -300" when I try to "Refresh entities" from  the widget.

Background:
- my device: Garmon Vivoactive 4 (I've set up local WiFi connection for it)
- I have a local HA installation (on raspberry pi)
- I've defined a local domain via router DNS ("hass")
- I've created a self-signed cert and uploaded it to the android device I use for Connect/ConnectIQ (I've checked so connections to HA (https://hass:8123) from my android device are trusted)
- I've installed HassControl via ConnectIQ, set the HA url (https://hass:8123) and long-lived token

The problem
- I've created a group in HA with a single light entity, then added it in ControlIQ/HassControl settings - getting -300 when hitting "Settings -> Refresh Entities"
- I also tried with a scene, when  I hit "Scenes" it shows the one I defined, but when I click it, I'm getting -300

Didn't find any information that it's required to have a remote access to HA as a requirement, but it's the only guess I have. Any ideas? :)

Thanks!

**Comment by hatl** [comment]
unfortunately, a self-signed certificate wont work.
see here: https://github.com/hatl/hasscontrol/issues/17#issuecomment-1574907846
and here: https://github.com/hatl/hasscontrol/issues/17#issuecomment-1894111858

I'll add that info to the README
