### ISSUE TITLE
Can't open settings on touchscreen vivoactive 4s

### ISSUE THREAD

**Issue by chrissfoot** [hatl/hasscontrol#62]
I have this installed and working on my Vivoactive 4s but I can't get back into the settings to make changes. It's a touch screen watch but no amount of holding down on any screen seems to make any difference. All that happens is the scroll indicator on the left disappears. Am I doing something wrong or is this an issue?

**Comment by hatl** [comment]
hold the button on the bottom-right:
![image](https://github.com/hatl/hasscontrol/assets/70505/e14a07f9-fd69-408a-98bf-a9adc2a8ea6a)

**Comment by KostaMadorsky** [comment]
I am having the same issue on Epix Pro.

Once configured and the grout entities are loaded for the first time, there is no way to get into settings.
Long pressing on the bottom right button opens recent up by default on recent Garmin watches.

**Comment by hatl** [comment]
On the Epix Pro it's even labelled as menu 😉 

![Image](https://github.com/user-attachments/assets/34f8fb5f-a9bc-4c38-92cc-19d9f6aa4f1e)

**Comment by KostaMadorsky** [comment]
Oh, yeah, thanks, long pressing the button worked 🤦‍♂️

Not a single app I used had that mapped to app settings, so I completely forgot about it 😅
