### ISSUE TITLE
Bug - Can't access Widget Settings from watch

### ISSUE THREAD

**Issue by BrendanRomanDev** [hatl/hasscontrol#63]
~~I've successfully tested getting a group to show up on my Garmin Vivoactive 4. I wanted to use a 'test' group that already existed, and set up my 'living_room' group which contained a single light entity.~~

~~**The issue:**~~
~~- Now that I have one working group/entity in the watch (a single light in my living_room group), there is no way for me to access settings such as 'refresh entities' in the widget, as suggested in Readme.md.~~
~~- I have changed settings in the Garmin IQ app to point to any other group, but the widget does not update or refresh to show new group entities despite syncing.~~

## Issue 2:
- If you're in the widget and you decide to open the main menu and turn off your phone connection to "Phone: off", there is no way to return to your watch face. The widget displays a warning icon, and the bottom 'back' button does nothing. You'll have to restart your watch to get out of the widget in this condition.

Things I have tried:
- Restarting my watch
- Restarting all Garmin Apps and initiating a re-sync.
- Restarting my HA server entirely & reloading my group configuration
- Long pressing the menu button while in the widget: 
    - This _does_ open a settings menu, but the only settings option available is for push notifications.
    
 Note:
 - Uninstalling and re-installing the widget from my device & re-logging in did work, but I imagine this would be a frustrating enough user experience that it's worth noting.
 - When a group is comprised of _multiple_ entities, the settings menu appears as it should. I _think_ that the issue was that my group only had _one entity_, and under this condition the widget settings menu did not work.

I'm not sure if you'll be able to replicate, but worth mentioning as it caused me some confusion!

Another Note:
- Thank you for making and maintaining this fork. This is such a neat and useful Widget, and I'm seriously impressed with the quality so far.

**Comment by hatl** [comment]
Hi
I just checked in the simulator - holding the menu button opens the settings menu:
![image](https://github.com/hatl/hasscontrol/assets/70505/d3443a98-a6f9-425a-8d11-fb6c84b7437f)

Did you change the button assignment - or is it the default one?

For the secondary issue, I would need more time to investigate.

**Comment by BrendanRomanDev** [comment]
> Did you change the button assignment - or is it the default one?

@hatl 
Thank you sincerely for your help. Apologies for this delayed response, my github notifications have been buried beneath those related to my work repository. I was able to resolve the first issue with the latest watch software update.

> For the secondary issue, I would need more time to investigate.
This one still persists. A common cure-all for random Hass issues I've encountered is to toggle Garmin 'phone-off', then 'phone-on'.  It just so happens that doing this from within the Hass widget itself creates an inescapable menu sequence.

**Comment by hatl** [comment]
> This one still persists. A common cure-all for random Hass issues I've encountered is to toggle Garmin 'phone-off', then 'phone-on'. It just so happens that doing this from within the Hass widget itself makes the widget inescapable.

Just tried it on my watch: when turning the phone connection off, the widget exits after a short delay.
Are you using the latest version of hasscontrol?

**Comment by hatl** [comment]
no update since 1 month
