### ISSUE TITLE
Support for Edge 1000 please

### ISSUE THREAD

**Issue by jbyway** [hatl/hasscontrol#66]
Hi - any chance of please adding support for the Edge 1000 unit? Thanks in advance.

**Comment by hatl** [comment]
hi
unfortunately that's not possible.
the edge 1000 only supports an API level of 2.4 but at least 3.1.0 would be needed.

![image](https://github.com/user-attachments/assets/16899b80-5179-4cd5-9411-ab49aae0a0db)
