### ISSUE TITLE
The widget only works for a split second

### ISSUE THREAD

**Issue by wranzzon** [hatl/hasscontrol#69]
Hello. 

Im trying to get the widget to work, but as you can see in the video, it only works for a split second before I get an error. If I spam the button, I can just activate the scene before I get an error. I dont quite know how to advance. The video is unlisted, so no one else without the link will be able to see it. https://youtube.com/shorts/3qzO0qdFGcM?feature=share

**Comment by hatl** [comment]
hi
could you please share the configuration on home assistant - including the entity types.
i'll then try to reproduce the issue.

**Comment by wranzzon** [comment]
Hello! Thx for replying. I hope this is what you want. Im the noob king of noobs. However, I have had the widget work before my Home assistant crasched, and for some reason the backup doesnt work, and now with my new setup it doesnt work any more. This is from /homeassistant/configuration.yaml

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem


Unfortunately I have searched the fil editor for anything named entities, but I havent found anything. Please point me in the right direction and I will happily share the info.

**Comment by hatl** [comment]
no worries :slightly_smiling_face: 

the default way would be to set up a group within your configuration.yaml file, as described here: https://github.com/hatl/hasscontrol?tab=readme-ov-file#group-sync

installing the "Studio Code Server" addon makes it easy to modify the configuration.yaml
see: https://github.com/hassio-addons/addon-vscode/blob/main/vscode/DOCS.md

**Comment by wranzzon** [comment]
Ah ok. So if I understand it correctly, there are no groups in a fresh installation in Home assistant, a group is something I have to create my self, and since I haven't created any groups I guess I don't have any config section for groups to send? Is that a correct assumption?

**Comment by hatl** [comment]
exactly. you have to create the config section.

**Comment by wranzzon** [comment]
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
http:
  ssl_certificate: /ssl/fullch
![RDT_20241119_0801185618505307552268671](https://github.com/user-attachments/assets/882b93e6-b8c1-48c3-b5c1-dbe2dd1ebdc4)
![Uploading RDT_20241119_0801185618505307552268671.jpg…]()
ain.pem
  ssl_key: /ssl/privkey.pem
  group:
  garmin:
    name: Garmin
    entities:
      - switch.garagebelysning


This is what I pasted, but clearly I did something wrong, because I get this error

**Comment by wranzzon** [comment]
Ok, Last post look really weird, Im trying again. So this is what I tried to write in my configuration.yaml

.#. Loads default set of integrations. Do not remove.
default_config:

.#. Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  group:
  garmin:
    name: Garmin
    entities:
      - switch.garagebelysning


But when im checking my configuration I get 2 errors
![plt-v0-1tw9cgqu3t1e1](https://github.com/user-attachments/assets/1eaa76e6-7e1b-4c9a-a8be-43ed9771d9cb)

**Comment by aelg305** [comment]
did you pay attention to indentation?

the code from the post dosnt show but you should have some spaces after each line.

same with the http code...here is an example: https://www.home-assistant.io/integrations/http/

**Comment by wranzzon** [comment]
I'm sorry, but I can't do this. I have tried to read this page for like 20 times, I don't understand what to do at all. I'm sorry for wasting your time, but I don't think I can advance in this problem. Which sucks, because when I got it to work last time it work flawlessly, and was super easy to set up and I really like the app/widget. I appreciate you work and time you out in to this.

**Comment by hatl** [comment]
- install Studio Code Server addon and check "view in sidebar"
![image](https://github.com/user-attachments/assets/8bbd9eab-943f-4e9e-95d5-a0fdb80f4b34)
- launch it from the sidebar
- create the config somewhere in configuration.yml like this:
![image](https://github.com/user-attachments/assets/a6435b1d-7a06-495a-8014-40879925042a)
- then go to developer options and re-load all yaml configuration:
![image](https://github.com/user-attachments/assets/a3cedb02-0e01-4a8a-bfa4-d71428359027)

**Comment by wranzzon** [comment]
Thank you for not losing faith in me, I have successfully done what you have told me, and Home assistant does not complain when I check configuration. I will try to configure some entitites when I get home from work tomorrow. ( I work wierd hours) Thank you yet again.

**Comment by wranzzon** [comment]
Holy cow it work!!!! When using entities I can finally open my garagedoor using my watch. Thank you so so much. I havent got scenes to work, because it would have been awesome to be able to open the garage and turn on the light at the same time. But at this time, im just so so happy that this works. I dont have too much money, but I will donate $10 for all your help. I know its not much, but I hope you understand how much I appreciate your help.

**Comment by wranzzon** [comment]
![2024-11-28](https://github.com/user-attachments/assets/b1508766-9c89-4169-844a-d03e785a47ba)


and of curse, I cant even do that without running in to problems, Im contacting my bank right now. Or do you have a paypal account I can donate to?

**Comment by wranzzon** [comment]
It worked now. I just payed $10. I hope you have received them

**Comment by hatl** [comment]
thank you very much!
i'm glad that your config works now
