### ISSUE TITLE
[Feature request] Show the middle entity by default when opening the widget

### ISSUE THREAD

**Issue by andrespalumbo311** [hatl/hasscontrol#71]
I think it might be handy to have the widget show the "middle" entity by default when opening it. For example, let's say i have 3 lights light.a light.b light.c i'll have the group configured like this:

> group:
>   garmin:
>     name: Garmin
>     entities:
>       - light.a
>       - light.b
>       - light.c
> 

When opening the widget I'll have light.a as the first entity to interact with, then light.b if i click "down", then light.c if i click "down" again, If the default was instead light.b I could get to light.a by clicking "up", and to light.c by clicking "down", having 2 entities i could get to within one click, while now I have to click two times to get to light.c
This is surely a very minor issue, especially with just 3 entities, but I still think it would be more convenient, and with more entities, let's say five, the difference would be greater, so it might make sense to consider this.
Thank you very much

**Comment by hatl** [comment]
yes, there's also an "up" button :slightly_smiling_face:
